export const COLOR_PARAMETERS = [
  ["base","Base","Normal"],["base_gradient_bottom","Base Gradient Bottom","Normal"],["base_gradient_top","Base Gradient Top","Normal"],["pattern","Pattern","Normal"],["pattern_gradient_top","Pattern Gradient Top","Normal"],["pattern_fill","Pattern Fill","Normal"],["masked_light_pattern","Masked Light Pattern","Normal"],
  ["newborn_base","Newborn Base","Newborn"],["newborn_base_gradient_bottom","Newborn Base Gradient Bottom","Newborn"],["newborn_base_gradient_top","Newborn Base Gradient Top","Newborn"],["newborn_pattern","Newborn Pattern","Newborn"],["newborn_pattern_gradient_top","Newborn Pattern Gradient Top","Newborn"],["newborn_pattern_fill","Newborn Pattern Fill","Newborn"],
  ["smoke_base","Smoke Base","Smoke"],["smoke_base_gradient_top","Smoke Base Gradient Top","Smoke"],["smoke_base_gradient_bottom","Smoke Base Gradient Bottom","Smoke"],["smoke_pattern","Smoke Pattern","Smoke"],["smoke_pattern_gradient_top","Smoke Pattern Gradient Top","Smoke"],
  ["freckled_pattern_gradient_top","Freckled Pattern Gradient Top","Freckled"],
  ["exotic_base","Exotic Base","Exotic"],["exotic_base_gradient_bottom","Exotic Base Gradient Bottom","Exotic"],["exotic_base_gradient_top","Exotic Base Gradient Top","Exotic"],["exotic_pattern","Exotic Pattern","Exotic"],["exotic_pattern_gradient_top","Exotic Pattern Gradient Top","Exotic"],["exotic_pattern_fill","Exotic Pattern Fill","Exotic"],["exotic_pattern_fill_gradient_top","Exotic Pattern Fill Gradient Top","Exotic"],["exotic_light_pattern","Exotic Light Pattern","Exotic"],["exotic_muzzle","Exotic Muzzle","Exotic"],
  ["newborn_exotic_base","Newborn Exotic Base","Newborn Exotic"],["newborn_exotic_base_gradient_bottom","Newborn Exotic Base Gradient Bottom","Newborn Exotic"],["newborn_exotic_base_gradient_top","Newborn Exotic Base Gradient Top","Newborn Exotic"],["newborn_exotic_pattern","Newborn Exotic Pattern","Newborn Exotic"],["newborn_exotic_pattern_gradient_top","Newborn Exotic Pattern Gradient Top","Newborn Exotic"],["newborn_exotic_pattern_fill","Newborn Exotic Pattern Fill","Newborn Exotic"],["newborn_exotic_pattern_fill_gradient_top","Newborn Exotic Pattern Fill Gradient Top","Newborn Exotic"],["newborn_exotic_light_pattern","Newborn Exotic Light Pattern","Newborn Exotic"],["newborn_exotic_muzzle","Newborn Exotic Muzzle","Newborn Exotic"]
].map(([id,label,group]) => ({id,label,group}));

export const PATTERN_COLOR_MAP = {
  0: "base",
  1: "base_gradient_bottom",
  2: "base_gradient_top",
  3: "pattern",
  4: "pattern_gradient_top",
  5: "pattern_fill",
  6: "masked_light_pattern",
  7: "newborn_base",
  8: "newborn_base_gradient_bottom",
  9: "newborn_base_gradient_top",
  10: "newborn_pattern",
  11: "newborn_pattern_gradient_top",
  12: "newborn_pattern_fill",
  13: "smoke_base",
  14: "smoke_base_gradient_top",
  15: "smoke_base_gradient_bottom",
  16: "smoke_pattern",
  17: "smoke_pattern_gradient_top",
  18: "freckled_pattern_gradient_top",
  19: "exotic_base",
  20: "exotic_base_gradient_bottom",
  21: "exotic_base_gradient_top",
  22: "exotic_pattern",
  23: "exotic_pattern_gradient_top",
  24: "exotic_pattern_fill",
  25: "exotic_pattern_fill_gradient_top",
  26: "exotic_light_pattern",
  27: "exotic_muzzle",
  28: "newborn_exotic_base",
  29: "newborn_exotic_base_gradient_bottom",
  30: "newborn_exotic_base_gradient_top",
  31: "newborn_exotic_pattern",
  32: "newborn_exotic_pattern_gradient_top",
  33: "newborn_exotic_pattern_fill",
  34: "newborn_exotic_pattern_fill_gradient_top",
  35: "newborn_exotic_light_pattern",
  36: "newborn_exotic_muzzle",
  37: "maskedchin",
  38: "sokokepatternfillgrad",
  39: "legbottomgrad",
  40: "backtailpatterngrad",
  41: "legpatterngrad"
};