export const PATTERNS = [
  { id: "BASEMASK", label: "Basemask", index: 0, groupX: 0, groupY: 0 },
  { id: "SIMPLEBOTTOMGRAD", label: "Simplebottomgrad", index: 1, groupX: 0, groupY: 0 },
  { id: "SIMPLETOPGRAD", label: "Simpletopgrad", index: 2, groupX: 0, groupY: 0 },
  { id: "BASICPATTERNGRAD", label: "Basicpatterngrad", index: 3, groupX: 0, groupY: 0 },
  { id: "TABBYPATTERN", label: "Tabbypattern", index: 4, groupX: 0, groupY: 0 },
  { id: "TICKEDPATTERN", label: "Tickedpattern", index: 5, groupX: 0, groupY: 0 },
  { id: "TICKEDSTRIPEFADE", label: "Tickedstripefade", index: 6, groupX: 0, groupY: 0 },
  { id: "TICKEDDOTS", label: "Tickeddots", index: 7, groupX: 0, groupY: 0 },
  { id: "TICKEDTOPGRAD", label: "Tickedtopgrad", index: 8, groupX: 0, groupY: 0 },
  { id: "SINGLESTRIPEPATTERN", label: "Singlestripepattern", index: 9, groupX: 0, groupY: 0 },
  { id: "SINGLESTRIPEPATTERNFADE", label: "Singlestripepatternfade", index: 10, groupX: 1, groupY: 0 },
  { id: "SOKOKEPATTERNGRAD", label: "Sokokepatterngrad", index: 11, groupX: 1, groupY: 0 },
  { id: "SOKOKEPATTERN", label: "Sokokepattern", index: 12, groupX: 1, groupY: 0 },
  { id: "SOKOKEPATTERNFILL", label: "Sokokepatternfill", index: 13, groupX: 1, groupY: 0 },
  { id: "SMOKEPATTERNGRAD", label: "Smokepatterngrad", index: 14, groupX: 1, groupY: 0 },
  { id: "SMOKEPATTERNDARK", label: "Smokepatterndark", index: 15, groupX: 1, groupY: 0 },
  { id: "SMOKEPATTERNLIGHT", label: "Smokepatternlight", index: 16, groupX: 1, groupY: 0 },
  { id: "SMOKETOPGRAD", label: "Smoketopgrad", index: 17, groupX: 1, groupY: 0 },
  { id: "SPECKLEDPATTERN", label: "Speckledpattern", index: 18, groupX: 1, groupY: 0 },
  { id: "ROSETTEPATTERN", label: "Rosettepattern", index: 19, groupX: 1, groupY: 0 },
  { id: "ROSETTEPATTERNFILL", label: "Rosettepatternfill", index: 20, groupX: 1, groupY: 0 },
  { id: "MASKEDPATTERN", label: "Maskedpattern", index: 21, groupX: 1, groupY: 0 },
  { id: "MASKEDPATTERNLIGHT", label: "Maskedpatternlight", index: 22, groupX: 1, groupY: 0 },
  { id: "MACKERELPATTERN", label: "Mackerelpattern", index: 23, groupX: 1, groupY: 0 },
  { id: "CLASSICPATTERN", label: "Classicpattern", index: 24, groupX: 1, groupY: 0 },
  { id: "AGOUTIPATTERN", label: "Agoutipattern", index: 25, groupX: 1, groupY: 0 },
  { id: "EXOTICBOTTOMGRAD", label: "Exoticbottomgrad", index: 26, groupX: 1, groupY: 0 },
  { id: "EXOTICTOPGRAD", label: "Exotictopgrad", index: 27, groupX: 1, groupY: 0 },
  { id: "BENGALPATTERN", label: "Bengalpattern", index: 28, groupX: 1, groupY: 0 },
  { id: "EXOTICPATTERNLIGHT", label: "Exoticpatternlight", index: 29, groupX: 1, groupY: 0 },
  { id: "EXOTICMUZZLE", label: "Exoticmuzzle", index: 30, groupX: 1, groupY: 0 },
  { id: "MARBLEDPATTERN", label: "Marbledpattern", index: 31, groupX: 1, groupY: 0 },
  { id: "MARBLEDPATTERNFILL", label: "Marbledpatternfill", index: 32, groupX: 1, groupY: 0 },
  { id: "FRECKLEDPATTERNBODY", label: "Freckledpatternbody", index: 33, groupX: 1, groupY: 0 },
  { id: "FRECKLEDPATTERNBACK", label: "Freckledpatternback", index: 34, groupX: 1, groupY: 0 },
  { id: "FRECKLEDPATTERNGRAD", label: "Freckledpatterngrad", index: 35, groupX: 1, groupY: 0 },
  { id: "BENGALPATTERNFILL", label: "Bengalpatternfill", index: 36, groupX: 1, groupY: 0 },
  { id: "MASKEDCHIN", label: "Maskedchin", index: 37, groupX: 1, groupY: 0 },
  { id: "SOKOKEPATTERNFILLGRAD", label: "Sokokepatternfillgrad", index: 38, groupX: 1, groupY: 0 },
  { id: "LEGBOTTOMGRAD", label: "Legbottomgrad", index: 39, groupX: 1, groupY: 0 },
  { id: "BACKTAILPATTERNGRAD", label: "Backtailpatterngrad", index: 40, groupX: 1, groupY: 0 },
  { id: "LEGPATTERNGRAD", label: "Legpatterngrad", index: 41, groupX: 1, groupY: 0 }
];

export const POSES = [
  { id: "newborn0", label: "Newborn", index: 0 },
  { id: "newborn1", label: "Newborn 1", index: 1 },
  { id: "newborn2", label: "Newborn 2", index: 2 },
  { id: "kitten0", label: "Kitten", index: 4 },
  { id: "kitten1", label: "Kitten 1", index: 5 },
  { id: "kitten2", label: "Kitten 2", index: 6 },
  { id: "sick_kitten0", label: "Sick Kitten", index: 7 },
  { id: "adolescent_short0", label: "Adolescent Short", index: 8 },
  { id: "adolescent_short1", label: "Adolescent Short 1", index: 9 },
  { id: "adolescent_short2", label: "Adolescent Short 2", index: 10 },
  { id: "sick_adolescent0", label: "Sick Adolescent", index: 11 },
  { id: "adolescent_long0", label: "Adolescent Long", index: 12 },
  { id: "adolescent_long1", label: "Adolescent Long 1", index: 13 },
  { id: "adolescent_long2", label: "Adolescent Long 2", index: 14 },
  { id: "adult_short0", label: "Adult Short", index: 16 },
  { id: "adult_short1", label: "Adult Short 1", index: 17 },
  { id: "adult_short2", label: "Adult Short 2", index: 18 },
  { id: "sick_adult0", label: "Sick Adult", index: 19 },
  { id: "adult_long0", label: "Adult Long", index: 20 },
  { id: "adult_long1", label: "Adult Long 1", index: 21 },
  { id: "adult_long2", label: "Adult Long 2", index: 22 },
  { id: "senior0", label: "Senior", index: 24 },
  { id: "senior1", label: "Senior 1", index: 25},
  { id: "senior2", label: "Senior 2", index: 26 },
  { id: "sick_senior0", label: "Sick Senior", index: 27 },
  { id: "para_adult_short0", label: "Paralyzed Adult Short", index: 28 },
  { id: "para_adult_long0", label: "Paralyzed Adult Long", index: 29 },
  { id: "para_young0", label: "Paralyzed Young", index: 30 }
];